check if protoc is in ci
Signed-off-by: Cassandra Coyle <cassie@diagrid.io>

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -109,6 +109,8 @@ jobs:
         /home/runner/.local/bin/toxiproxy-server --version
     - name: Clean up files
       run: ./mvnw clean -B
+    - name: Check protoc version
+      run: protoc --version || echo "protoc not found"
     - name: Build sdk
       run: ./mvnw compile -B -q
     - name: Unit tests
